# Generated by Django 3.2.8 on 2021-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiezapp', '0002_alter_cakecookiez_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakecookiez',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='cakecookiez',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
