# Generated by Django 3.2.8 on 2021-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiezapp', '0003_auto_20211115_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakecookiez',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
